// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hsm/v1/key.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyMetadata defines the key pair metadata.
type KeyMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid is the unique identifier of the key pair.
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// algorithm is the algorithm used for the key pair, e.g. "ECDSA", etc.
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// created_at is the timestamp of the creation of the key pair.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the timestamp of the last update of the key pair.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// version is the key pair version, updated each time the key pair is rotated.
	Version       int32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyMetadata) Reset() {
	*x = KeyMetadata{}
	mi := &file_hsm_v1_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMetadata) ProtoMessage() {}

func (x *KeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMetadata.ProtoReflect.Descriptor instead.
func (*KeyMetadata) Descriptor() ([]byte, []int) {
	return file_hsm_v1_key_proto_rawDescGZIP(), []int{0}
}

func (x *KeyMetadata) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *KeyMetadata) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *KeyMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KeyMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KeyMetadata) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_hsm_v1_key_proto protoreflect.FileDescriptor

const file_hsm_v1_key_proto_rawDesc = "" +
	"\n" +
	"\x10hsm/v1/key.proto\x12\x06hsm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n" +
	"\vKeyMetadata\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversionB'Z%github.com/DaevMithran/mini-hsm/typesb\x06proto3"

var (
	file_hsm_v1_key_proto_rawDescOnce sync.Once
	file_hsm_v1_key_proto_rawDescData []byte
)

func file_hsm_v1_key_proto_rawDescGZIP() []byte {
	file_hsm_v1_key_proto_rawDescOnce.Do(func() {
		file_hsm_v1_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hsm_v1_key_proto_rawDesc), len(file_hsm_v1_key_proto_rawDesc)))
	})
	return file_hsm_v1_key_proto_rawDescData
}

var file_hsm_v1_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hsm_v1_key_proto_goTypes = []any{
	(*KeyMetadata)(nil),           // 0: hsm.v1.KeyMetadata
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_hsm_v1_key_proto_depIdxs = []int32{
	1, // 0: hsm.v1.KeyMetadata.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: hsm.v1.KeyMetadata.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hsm_v1_key_proto_init() }
func file_hsm_v1_key_proto_init() {
	if File_hsm_v1_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hsm_v1_key_proto_rawDesc), len(file_hsm_v1_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hsm_v1_key_proto_goTypes,
		DependencyIndexes: file_hsm_v1_key_proto_depIdxs,
		MessageInfos:      file_hsm_v1_key_proto_msgTypes,
	}.Build()
	File_hsm_v1_key_proto = out.File
	file_hsm_v1_key_proto_goTypes = nil
	file_hsm_v1_key_proto_depIdxs = nil
}
