// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: hsm/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_ListKeys_FullMethodName            = "/hsm.v1.Query/ListKeys"
	Query_GetPublicKey_FullMethodName        = "/hsm.v1.Query/GetPublicKey"
	Query_GetPublicKeyVersion_FullMethodName = "/hsm.v1.Query/GetPublicKeyVersion"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service for the hsm.v1 module.
type QueryClient interface {
	// Fetch the list of all key pairs metadata.
	ListKeys(ctx context.Context, in *QueryListKeysRequest, opts ...grpc.CallOption) (*QueryListKeysResponse, error)
	// Fetch the latest version of the public key for a given kid.
	GetPublicKey(ctx context.Context, in *QueryGetPublicKeyRequest, opts ...grpc.CallOption) (*QueryGetPublicKeyResponse, error)
	// Fetch a specific version of the public key for a given kid.
	GetPublicKeyVersion(ctx context.Context, in *QueryGetPublicKeyVersionRequest, opts ...grpc.CallOption) (*QueryGetPublicKeyVersionResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ListKeys(ctx context.Context, in *QueryListKeysRequest, opts ...grpc.CallOption) (*QueryListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListKeysResponse)
	err := c.cc.Invoke(ctx, Query_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPublicKey(ctx context.Context, in *QueryGetPublicKeyRequest, opts ...grpc.CallOption) (*QueryGetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetPublicKeyResponse)
	err := c.cc.Invoke(ctx, Query_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPublicKeyVersion(ctx context.Context, in *QueryGetPublicKeyVersionRequest, opts ...grpc.CallOption) (*QueryGetPublicKeyVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetPublicKeyVersionResponse)
	err := c.cc.Invoke(ctx, Query_GetPublicKeyVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service for the hsm.v1 module.
type QueryServer interface {
	// Fetch the list of all key pairs metadata.
	ListKeys(context.Context, *QueryListKeysRequest) (*QueryListKeysResponse, error)
	// Fetch the latest version of the public key for a given kid.
	GetPublicKey(context.Context, *QueryGetPublicKeyRequest) (*QueryGetPublicKeyResponse, error)
	// Fetch a specific version of the public key for a given kid.
	GetPublicKeyVersion(context.Context, *QueryGetPublicKeyVersionRequest) (*QueryGetPublicKeyVersionResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) ListKeys(context.Context, *QueryListKeysRequest) (*QueryListKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedQueryServer) GetPublicKey(context.Context, *QueryGetPublicKeyRequest) (*QueryGetPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedQueryServer) GetPublicKeyVersion(context.Context, *QueryGetPublicKeyVersionRequest) (*QueryGetPublicKeyVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicKeyVersion not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListKeys(ctx, req.(*QueryListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPublicKey(ctx, req.(*QueryGetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPublicKeyVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPublicKeyVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPublicKeyVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetPublicKeyVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPublicKeyVersion(ctx, req.(*QueryGetPublicKeyVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hsm.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListKeys",
			Handler:    _Query_ListKeys_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _Query_GetPublicKey_Handler,
		},
		{
			MethodName: "GetPublicKeyVersion",
			Handler:    _Query_GetPublicKeyVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hsm/v1/query.proto",
}
