// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hsm/v1/query.proto

package types

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryListKeysRequest defines the Query/ListKeys request type.
type QueryListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListKeysRequest) Reset() {
	*x = QueryListKeysRequest{}
	mi := &file_hsm_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListKeysRequest) ProtoMessage() {}

func (x *QueryListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListKeysRequest.ProtoReflect.Descriptor instead.
func (*QueryListKeysRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryListKeysResponse defines the Query/ListKeys response type.
type QueryListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyMetadata         `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryListKeysResponse) Reset() {
	*x = QueryListKeysResponse{}
	mi := &file_hsm_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryListKeysResponse) ProtoMessage() {}

func (x *QueryListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryListKeysResponse.ProtoReflect.Descriptor instead.
func (*QueryListKeysResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryListKeysResponse) GetKeys() []*KeyMetadata {
	if x != nil {
		return x.Keys
	}
	return nil
}

// QueryGetPublicKeyRequest defines the Query/GetPublicKey request type.
type QueryGetPublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid is the unique identifier of the key pair.
	// UUID format, e.g. "123e4567-e89b-12d3-a456-426614174000".
	Kid           string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetPublicKeyRequest) Reset() {
	*x = QueryGetPublicKeyRequest{}
	mi := &file_hsm_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetPublicKeyRequest) ProtoMessage() {}

func (x *QueryGetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*QueryGetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryGetPublicKeyRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

// QueryGetPublicKeyResponse defines the Query/GetPublicKey response type.
type QueryGetPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key_pem is the PEM-encoded public key.
	PublicKeyPem  string `protobuf:"bytes,1,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetPublicKeyResponse) Reset() {
	*x = QueryGetPublicKeyResponse{}
	mi := &file_hsm_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetPublicKeyResponse) ProtoMessage() {}

func (x *QueryGetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*QueryGetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGetPublicKeyResponse) GetPublicKeyPem() string {
	if x != nil {
		return x.PublicKeyPem
	}
	return ""
}

// QueryGetPublicKeyVersionRequest defines the Query/GetPublicKeyVersion request type.
type QueryGetPublicKeyVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid is the unique identifier of the key pair.
	// UUID format, e.g. "123e4567-e89b-12d3-a456-426614174000".
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// key pair version, e.g. "1", "2", etc.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetPublicKeyVersionRequest) Reset() {
	*x = QueryGetPublicKeyVersionRequest{}
	mi := &file_hsm_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetPublicKeyVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetPublicKeyVersionRequest) ProtoMessage() {}

func (x *QueryGetPublicKeyVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetPublicKeyVersionRequest.ProtoReflect.Descriptor instead.
func (*QueryGetPublicKeyVersionRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryGetPublicKeyVersionRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *QueryGetPublicKeyVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// QueryGetPublicKeyVersionResponse defines the Query/GetPublicKeyVersion response type.
type QueryGetPublicKeyVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key_pem is the PEM-encoded public key.
	PublicKeyPem  string `protobuf:"bytes,1,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetPublicKeyVersionResponse) Reset() {
	*x = QueryGetPublicKeyVersionResponse{}
	mi := &file_hsm_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetPublicKeyVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetPublicKeyVersionResponse) ProtoMessage() {}

func (x *QueryGetPublicKeyVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetPublicKeyVersionResponse.ProtoReflect.Descriptor instead.
func (*QueryGetPublicKeyVersionResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryGetPublicKeyVersionResponse) GetPublicKeyPem() string {
	if x != nil {
		return x.PublicKeyPem
	}
	return ""
}

var File_hsm_v1_query_proto protoreflect.FileDescriptor

const file_hsm_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x12hsm/v1/query.proto\x12\x06hsm.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x10hsm/v1/key.proto\"\x16\n" +
	"\x14QueryListKeysRequest\"@\n" +
	"\x15QueryListKeysResponse\x12'\n" +
	"\x04keys\x18\x01 \x03(\v2\x13.hsm.v1.KeyMetadataR\x04keys\",\n" +
	"\x18QueryGetPublicKeyRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\"A\n" +
	"\x19QueryGetPublicKeyResponse\x12$\n" +
	"\x0epublic_key_pem\x18\x01 \x01(\tR\fpublicKeyPem\"M\n" +
	"\x1fQueryGetPublicKeyVersionRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"H\n" +
	" QueryGetPublicKeyVersionResponse\x12$\n" +
	"\x0epublic_key_pem\x18\x01 \x01(\tR\fpublicKeyPem2\xf0\x02\n" +
	"\x05Query\x12]\n" +
	"\bListKeys\x12\x1c.hsm.v1.QueryListKeysRequest\x1a\x1d.hsm.v1.QueryListKeysResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/hsm/v1/keys\x12o\n" +
	"\fGetPublicKey\x12 .hsm.v1.QueryGetPublicKeyRequest\x1a!.hsm.v1.QueryGetPublicKeyResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/hsm/v1/keys/{kid}\x12\x96\x01\n" +
	"\x13GetPublicKeyVersion\x12'.hsm.v1.QueryGetPublicKeyVersionRequest\x1a(.hsm.v1.QueryGetPublicKeyVersionResponse\",\x82\xd3\xe4\x93\x02&\x12$/hsm/v1/keys/{kid}/version/{version}B'Z%github.com/DaevMithran/mini-hsm/typesb\x06proto3"

var (
	file_hsm_v1_query_proto_rawDescOnce sync.Once
	file_hsm_v1_query_proto_rawDescData []byte
)

func file_hsm_v1_query_proto_rawDescGZIP() []byte {
	file_hsm_v1_query_proto_rawDescOnce.Do(func() {
		file_hsm_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hsm_v1_query_proto_rawDesc), len(file_hsm_v1_query_proto_rawDesc)))
	})
	return file_hsm_v1_query_proto_rawDescData
}

var file_hsm_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hsm_v1_query_proto_goTypes = []any{
	(*QueryListKeysRequest)(nil),             // 0: hsm.v1.QueryListKeysRequest
	(*QueryListKeysResponse)(nil),            // 1: hsm.v1.QueryListKeysResponse
	(*QueryGetPublicKeyRequest)(nil),         // 2: hsm.v1.QueryGetPublicKeyRequest
	(*QueryGetPublicKeyResponse)(nil),        // 3: hsm.v1.QueryGetPublicKeyResponse
	(*QueryGetPublicKeyVersionRequest)(nil),  // 4: hsm.v1.QueryGetPublicKeyVersionRequest
	(*QueryGetPublicKeyVersionResponse)(nil), // 5: hsm.v1.QueryGetPublicKeyVersionResponse
	(*KeyMetadata)(nil),                      // 6: hsm.v1.KeyMetadata
}
var file_hsm_v1_query_proto_depIdxs = []int32{
	6, // 0: hsm.v1.QueryListKeysResponse.keys:type_name -> hsm.v1.KeyMetadata
	0, // 1: hsm.v1.Query.ListKeys:input_type -> hsm.v1.QueryListKeysRequest
	2, // 2: hsm.v1.Query.GetPublicKey:input_type -> hsm.v1.QueryGetPublicKeyRequest
	4, // 3: hsm.v1.Query.GetPublicKeyVersion:input_type -> hsm.v1.QueryGetPublicKeyVersionRequest
	1, // 4: hsm.v1.Query.ListKeys:output_type -> hsm.v1.QueryListKeysResponse
	3, // 5: hsm.v1.Query.GetPublicKey:output_type -> hsm.v1.QueryGetPublicKeyResponse
	5, // 6: hsm.v1.Query.GetPublicKeyVersion:output_type -> hsm.v1.QueryGetPublicKeyVersionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hsm_v1_query_proto_init() }
func file_hsm_v1_query_proto_init() {
	if File_hsm_v1_query_proto != nil {
		return
	}
	file_hsm_v1_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hsm_v1_query_proto_rawDesc), len(file_hsm_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hsm_v1_query_proto_goTypes,
		DependencyIndexes: file_hsm_v1_query_proto_depIdxs,
		MessageInfos:      file_hsm_v1_query_proto_msgTypes,
	}.Build()
	File_hsm_v1_query_proto = out.File
	file_hsm_v1_query_proto_goTypes = nil
	file_hsm_v1_query_proto_depIdxs = nil
}
