// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hsm/v1/tx.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateKeyRequest defines the Msg/CreateKey request type.
// It describes the parameters of a request for creating a new key pair.
type MsgCreateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateKeyRequest) Reset() {
	*x = MsgCreateKeyRequest{}
	mi := &file_hsm_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateKeyRequest) ProtoMessage() {}

func (x *MsgCreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateKeyRequest.ProtoReflect.Descriptor instead.
func (*MsgCreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{0}
}

// MsgCreateKeyResponse defines the Msg/CreateKey response type.
type MsgCreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *KeyMetadata           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateKeyResponse) Reset() {
	*x = MsgCreateKeyResponse{}
	mi := &file_hsm_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateKeyResponse) ProtoMessage() {}

func (x *MsgCreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateKeyResponse) GetKey() *KeyMetadata {
	if x != nil {
		return x.Key
	}
	return nil
}

// MsgRotateKeyRequest defines the Msg/RotateKey request type.
// It describes the parameters of a request for rotating a key pair for a given kid.
type MsgRotateKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid is the unique identifier of the key pair.
	// UUID format, e.g. "123e4567-e89b-12d3-a456-426614174000".
	Kid           string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRotateKeyRequest) Reset() {
	*x = MsgRotateKeyRequest{}
	mi := &file_hsm_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRotateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRotateKeyRequest) ProtoMessage() {}

func (x *MsgRotateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRotateKeyRequest.ProtoReflect.Descriptor instead.
func (*MsgRotateKeyRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRotateKeyRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

// MsgRotateKeyResponse defines the Msg/RotateKey response type.
type MsgRotateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *KeyMetadata           `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRotateKeyResponse) Reset() {
	*x = MsgRotateKeyResponse{}
	mi := &file_hsm_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRotateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRotateKeyResponse) ProtoMessage() {}

func (x *MsgRotateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRotateKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgRotateKeyResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgRotateKeyResponse) GetMetadata() *KeyMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MsgSignRequest defines the Msg/Sign request type.
// It describes the parameters of a request for signing a message using a kid and the latest version
type MsgSignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid is the unique identifier of the key pair.
	// UUID format, e.g. "123e4567-e89b-12d3-a456-426614174000".
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// data is the payload to be signed.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSignRequest) Reset() {
	*x = MsgSignRequest{}
	mi := &file_hsm_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSignRequest) ProtoMessage() {}

func (x *MsgSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSignRequest.ProtoReflect.Descriptor instead.
func (*MsgSignRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgSignRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *MsgSignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MsgSignResponse defines the Msg/Sign response type.
type MsgSignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signature is generated using the private key corresponding to the given kid.
	Signature     []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSignResponse) Reset() {
	*x = MsgSignResponse{}
	mi := &file_hsm_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSignResponse) ProtoMessage() {}

func (x *MsgSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSignResponse.ProtoReflect.Descriptor instead.
func (*MsgSignResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MsgVerifyRequest defines the Msg/Verify request type.
// It describes the parameters of a request for verifying a signature using a kid and the latest version
type MsgVerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kid is the unique identifier of the key pair.
	// UUID format, e.g. "123e4567-e89b-12d3-a456-426614174000".
	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	// data is the payload that was signed.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// signature is the signature to be verified.
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVerifyRequest) Reset() {
	*x = MsgVerifyRequest{}
	mi := &file_hsm_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVerifyRequest) ProtoMessage() {}

func (x *MsgVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVerifyRequest.ProtoReflect.Descriptor instead.
func (*MsgVerifyRequest) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgVerifyRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *MsgVerifyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgVerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MsgVerifyResponse defines the Msg/Verify response type.
type MsgVerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// valid indicates whether the signature is valid.
	Valid         bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVerifyResponse) Reset() {
	*x = MsgVerifyResponse{}
	mi := &file_hsm_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVerifyResponse) ProtoMessage() {}

func (x *MsgVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hsm_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVerifyResponse.ProtoReflect.Descriptor instead.
func (*MsgVerifyResponse) Descriptor() ([]byte, []int) {
	return file_hsm_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgVerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_hsm_v1_tx_proto protoreflect.FileDescriptor

const file_hsm_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x0fhsm/v1/tx.proto\x12\x06hsm.v1\x1a\x10hsm/v1/key.proto\"\x15\n" +
	"\x13MsgCreateKeyRequest\"=\n" +
	"\x14MsgCreateKeyResponse\x12%\n" +
	"\x03key\x18\x01 \x01(\v2\x13.hsm.v1.KeyMetadataR\x03key\"'\n" +
	"\x13MsgRotateKeyRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\"G\n" +
	"\x14MsgRotateKeyResponse\x12/\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.hsm.v1.KeyMetadataR\bmetadata\"6\n" +
	"\x0eMsgSignRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"/\n" +
	"\x0fMsgSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"V\n" +
	"\x10MsgVerifyRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\")\n" +
	"\x11MsgVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\x8d\x02\n" +
	"\x03Msg\x12F\n" +
	"\tCreateKey\x12\x1b.hsm.v1.MsgCreateKeyRequest\x1a\x1c.hsm.v1.MsgCreateKeyResponse\x12F\n" +
	"\tRotateKey\x12\x1b.hsm.v1.MsgRotateKeyRequest\x1a\x1c.hsm.v1.MsgRotateKeyResponse\x127\n" +
	"\x04Sign\x12\x16.hsm.v1.MsgSignRequest\x1a\x17.hsm.v1.MsgSignResponse\x12=\n" +
	"\x06Verify\x12\x18.hsm.v1.MsgVerifyRequest\x1a\x19.hsm.v1.MsgVerifyResponseB'Z%github.com/DaevMithran/mini-hsm/typesb\x06proto3"

var (
	file_hsm_v1_tx_proto_rawDescOnce sync.Once
	file_hsm_v1_tx_proto_rawDescData []byte
)

func file_hsm_v1_tx_proto_rawDescGZIP() []byte {
	file_hsm_v1_tx_proto_rawDescOnce.Do(func() {
		file_hsm_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hsm_v1_tx_proto_rawDesc), len(file_hsm_v1_tx_proto_rawDesc)))
	})
	return file_hsm_v1_tx_proto_rawDescData
}

var file_hsm_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hsm_v1_tx_proto_goTypes = []any{
	(*MsgCreateKeyRequest)(nil),  // 0: hsm.v1.MsgCreateKeyRequest
	(*MsgCreateKeyResponse)(nil), // 1: hsm.v1.MsgCreateKeyResponse
	(*MsgRotateKeyRequest)(nil),  // 2: hsm.v1.MsgRotateKeyRequest
	(*MsgRotateKeyResponse)(nil), // 3: hsm.v1.MsgRotateKeyResponse
	(*MsgSignRequest)(nil),       // 4: hsm.v1.MsgSignRequest
	(*MsgSignResponse)(nil),      // 5: hsm.v1.MsgSignResponse
	(*MsgVerifyRequest)(nil),     // 6: hsm.v1.MsgVerifyRequest
	(*MsgVerifyResponse)(nil),    // 7: hsm.v1.MsgVerifyResponse
	(*KeyMetadata)(nil),          // 8: hsm.v1.KeyMetadata
}
var file_hsm_v1_tx_proto_depIdxs = []int32{
	8, // 0: hsm.v1.MsgCreateKeyResponse.key:type_name -> hsm.v1.KeyMetadata
	8, // 1: hsm.v1.MsgRotateKeyResponse.metadata:type_name -> hsm.v1.KeyMetadata
	0, // 2: hsm.v1.Msg.CreateKey:input_type -> hsm.v1.MsgCreateKeyRequest
	2, // 3: hsm.v1.Msg.RotateKey:input_type -> hsm.v1.MsgRotateKeyRequest
	4, // 4: hsm.v1.Msg.Sign:input_type -> hsm.v1.MsgSignRequest
	6, // 5: hsm.v1.Msg.Verify:input_type -> hsm.v1.MsgVerifyRequest
	1, // 6: hsm.v1.Msg.CreateKey:output_type -> hsm.v1.MsgCreateKeyResponse
	3, // 7: hsm.v1.Msg.RotateKey:output_type -> hsm.v1.MsgRotateKeyResponse
	5, // 8: hsm.v1.Msg.Sign:output_type -> hsm.v1.MsgSignResponse
	7, // 9: hsm.v1.Msg.Verify:output_type -> hsm.v1.MsgVerifyResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hsm_v1_tx_proto_init() }
func file_hsm_v1_tx_proto_init() {
	if File_hsm_v1_tx_proto != nil {
		return
	}
	file_hsm_v1_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hsm_v1_tx_proto_rawDesc), len(file_hsm_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hsm_v1_tx_proto_goTypes,
		DependencyIndexes: file_hsm_v1_tx_proto_depIdxs,
		MessageInfos:      file_hsm_v1_tx_proto_msgTypes,
	}.Build()
	File_hsm_v1_tx_proto = out.File
	file_hsm_v1_tx_proto_goTypes = nil
	file_hsm_v1_tx_proto_depIdxs = nil
}
