// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: hsm/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CreateKey_FullMethodName = "/hsm.v1.Msg/CreateKey"
	Msg_RotateKey_FullMethodName = "/hsm.v1.Msg/RotateKey"
	Msg_Sign_FullMethodName      = "/hsm.v1.Msg/Sign"
	Msg_Verify_FullMethodName    = "/hsm.v1.Msg/Verify"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the service for handling transactions for the hsm.v1 module.
type MsgClient interface {
	// CreateKey defines a method for creating a new key pair
	CreateKey(ctx context.Context, in *MsgCreateKeyRequest, opts ...grpc.CallOption) (*MsgCreateKeyResponse, error)
	// RotateKey defines a method for rotating a key pair for a given kid
	RotateKey(ctx context.Context, in *MsgRotateKeyRequest, opts ...grpc.CallOption) (*MsgRotateKeyResponse, error)
	// Sign defines a method for signing a message using a kid and the latest version of the key pair
	Sign(ctx context.Context, in *MsgSignRequest, opts ...grpc.CallOption) (*MsgSignResponse, error)
	// Verify defines a method for verifying a signature using a kid and the latest version of the key pair
	Verify(ctx context.Context, in *MsgVerifyRequest, opts ...grpc.CallOption) (*MsgVerifyResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateKey(ctx context.Context, in *MsgCreateKeyRequest, opts ...grpc.CallOption) (*MsgCreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateKeyResponse)
	err := c.cc.Invoke(ctx, Msg_CreateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RotateKey(ctx context.Context, in *MsgRotateKeyRequest, opts ...grpc.CallOption) (*MsgRotateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRotateKeyResponse)
	err := c.cc.Invoke(ctx, Msg_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Sign(ctx context.Context, in *MsgSignRequest, opts ...grpc.CallOption) (*MsgSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSignResponse)
	err := c.cc.Invoke(ctx, Msg_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Verify(ctx context.Context, in *MsgVerifyRequest, opts ...grpc.CallOption) (*MsgVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgVerifyResponse)
	err := c.cc.Invoke(ctx, Msg_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the service for handling transactions for the hsm.v1 module.
type MsgServer interface {
	// CreateKey defines a method for creating a new key pair
	CreateKey(context.Context, *MsgCreateKeyRequest) (*MsgCreateKeyResponse, error)
	// RotateKey defines a method for rotating a key pair for a given kid
	RotateKey(context.Context, *MsgRotateKeyRequest) (*MsgRotateKeyResponse, error)
	// Sign defines a method for signing a message using a kid and the latest version of the key pair
	Sign(context.Context, *MsgSignRequest) (*MsgSignResponse, error)
	// Verify defines a method for verifying a signature using a kid and the latest version of the key pair
	Verify(context.Context, *MsgVerifyRequest) (*MsgVerifyResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CreateKey(context.Context, *MsgCreateKeyRequest) (*MsgCreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedMsgServer) RotateKey(context.Context, *MsgRotateKeyRequest) (*MsgRotateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedMsgServer) Sign(context.Context, *MsgSignRequest) (*MsgSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedMsgServer) Verify(context.Context, *MsgVerifyRequest) (*MsgVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateKey(ctx, req.(*MsgCreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RotateKey(ctx, req.(*MsgRotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Sign(ctx, req.(*MsgSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Verify(ctx, req.(*MsgVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hsm.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKey",
			Handler:    _Msg_CreateKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _Msg_RotateKey_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Msg_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Msg_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hsm/v1/tx.proto",
}
